### ISSUE TITLE
makePrediction(instance) output on MTR

### ISSUE THREAD

**Issue by Rao2048** [kdis-lab/ExecuteMulan#4]
Hi. I created a model using multi target stacking from the algorithms/mtr with base model as REPTree. My input features are all numeric type. and I have 9 targets all numeric as well.
I get these values on printing the prediction values:
finalPredictions:[D@7b3300e5
mlo:[D@7382f612

I have the following questions:
1. How should we expect the predicted values for a multi target regressor from the code to look like?
2. Any clue on how to interpret the response I have got above?

Would be very helpful if I can get any insight regarding predictions for MTR.
Thanks in advance. :)

**Comment by i02momuj** [comment]
Hello.

The documentation of the Mulan library would help you a lot. In their sourceforge webpage, they have the (old) doc, where the MTR algorithms were not available but it could be helpful. The MultiLabelOutput object has several method tht you can use to obtain the prediction (http://mulan.sourceforge.net/doc/)

In GitHub you have the original Mulan extended library, which included the MTR algorithms (https://github.com/lefman/mulan-extended). Their authors may help you better, probably.

Best
